remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: FraMora
description: Under construction. Testing.
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
